travelbook/models.py
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from travelbook import db, login_manager, app
from flask_login import UserMixin


@login_manager.user_loader
def load_user(guide_id):
    return Guide.query.get(int(guide_id))


class Guide(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    surname = db.Column(db.String(20), nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(120), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    travels = db.relationship('Travel', backref='guide', lazy=True)

    def __repr__(self):
        return f'<Guide: {self.name} {self.surname}>'

    def insert(self):
        db.session.add(self)
        db.session.commit()

    def update(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)


class Travel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(40), nullable=False)
    content = db.Column(db.Text, nullable=False)
    guide_id = db.Column(db.Integer, db.ForeignKey('guide.id'), nullable=False)

    def __repr__(self):
        return f'<Travel: {self.title}>'

    def insert(self):
        db.session.add(self)
        db.session.commit()

    def update(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

travelbook/guides/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from travelbook.models import Guide


class RegistrationForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(min=3, max=20)])
    surname = StringField(
        'Surname',
        validators=[DataRequired(), Length(min=3, max=20)])
    phone = StringField(
        'Phone',
        validators=[DataRequired(), Length(min=9, max=15)])
    email = StringField(
        'Email',
        validators=[DataRequired()])
    password = PasswordField(
        'Password',
        validators=[DataRequired()])
    confirm_password = PasswordField(
        'Confirm Password',
        validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = Guide.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField(
        'Email',
        validators=[DataRequired(), Email()])
    password = PasswordField(
        'Password',
        validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class GuideForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(min=3, max=20)])
    surname = StringField(
        'Surname',
        validators=[DataRequired(), Length(min=3, max=20)])
    phone = StringField(
        'Phone',
        validators=[DataRequired(), Length(min=9, max=15)])
    email = StringField(
        'Email',
        validators=[DataRequired()])
    image_file = StringField(
        'image_file')
    picture = FileField(
        'Update Profile Picture',
        validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update Account')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = Guide.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')


class RequestResetForm(FlaskForm):
    email = StringField(
        'Email',
        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = Guide.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField(
        'Password',
        validators=[DataRequired()])
    confirm_password = PasswordField(
        'Confirm Password',
         validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

travelbook/travels/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class TravelForm(FlaskForm):
    title = StringField(
        'Title',
        validators=[DataRequired()])
    content = TextAreaField(
        'Content',
        validators=[DataRequired()])
    submit = SubmitField('Submit')

travelbook/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
# from travelbook.config import Config       # And when you can move all app.config variables + import os


database_name = "travelbook_login"
database_path = 'postgresql://postgres@localhost:5432/travelbook_login'

SECRET_KEY = os.urandom(32)


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = database_path
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = SECRET_KEY
db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
migrate = Migrate(app, db)
CORS(app)

login_manager = LoginManager(app)
# login_manager.login_view = 'login'   - If we don't use Blueprints
login_manager.login_view = 'guides.login'
login_manager.login_message_category = 'info'

app.config['MAIL_SERVER'] = 'smtp.googlemail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = os.environ.get('EMAIL_USER')
app.config['MAIL_PASSWORD'] = os.environ.get('EMAIL_PASS')

mail = Mail(app)


from travelbook.guides.routes import guides
from travelbook.travels.routes import travels
from travelbook.main.routes import main
from travelbook.errors.handlers import errors

app.register_blueprint(guides)
app.register_blueprint(travels)
app.register_blueprint(main)
app.register_blueprint(errors)

travelbook/guides/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from travelbook import db, bcrypt
from travelbook.models import Guide, Travel
from travelbook.guides.forms import (GuideForm, RegistrationForm, LoginForm,
                                        RequestResetForm, ResetPasswordForm)
from travelbook.guides.utils import save_picture, send_reset_email


guides = Blueprint('guides', __name__)


@guides.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        guide = Guide(name = form.name.data,
                    surname = form.surname.data,
                    phone = form.phone.data,
                    email = form.email.data,
                    password = hashed_password)
        try:
            guide.insert()
            flash('Guide' + form.name.data + ' ' + form.surname.data + ' was successfully created!', 'success')
            return redirect(url_for('guides.login'))
        except Exception:
            flash('An error occurred. Guide could not be created.', 'danger')
    return render_template('register.html', title='Register', form=form)


@guides.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Guide.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You have been logged in!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@guides.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@guides.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = GuideForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.name = form.name.data
        current_user.surname = form.surname.data
        current_user.phone = form.phone.data
        current_user.email = form.email.data
        current_user.update()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('guides.account'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.surname.data = current_user.surname
        form.phone.data = current_user.phone
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

#  All Guides
# ----------------------------------------------------------------#
@guides.route('/guides')
def all_guides():
    try:
        guides=Guide.query.all()
        for guide in guides:
            guide.image_file = url_for('static', filename='profile_pics/' + guide.image_file)
    except Exception:
        abort(404)
    return render_template('guides.html', guides=guides, title='Guides')

# Show Guide
# ----------------------------------------------------------------#
@guides.route('/guides/<guide_id>')
def show_guide(guide_id):
    guide = Guide.query.get_or_404(guide_id)
    travels = Travel.query.filter_by(guide_id=guide.id).all()
    guide.image_file = url_for('static', filename='profile_pics/' + guide.image_file)
    title = 'Guide ' + guide.name + ' ' + guide.surname
    return render_template('show_guide.html', guide=guide, travels=travels, title=title)

# Delete Guide
# ----------------------------------------------------------------#
@guides.route('/guides/<guide_id>', methods=['POST', 'DELETE'])
def delete_guide(guide_id):
    guide = Guide.query.get_or_404(guide_id)
    try:
        guide.delete()
        flash('Deleted!', 'success')
    except:
        flash('There was a problem deleting that guide', 'danger')
    return redirect('/guides')

# Only Guide's travels
# ----------------------------------------------------------------#
@guides.route("/my_travels")
@login_required
def guide_travels():
    page = request.args.get('page', 1, type=int)
    guide = current_user
    travels = Travel.query.filter_by(guide=guide)\
        .order_by(Travel.id.desc())\
        .paginate(page=page, per_page=3)
    return render_template('guide_travels.html', travels=travels, guide=guide)

# ----------------------------------------------------------------#
# Password reset
# ----------------------------------------------------------------#
@guides.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Guide.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('guides.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@guides.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Guide.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('guides.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        try:
            user.update()
            flash('Your password has been updated! You are now able to log in', 'success')
            return redirect(url_for('guides.login'))
        except Exception:
            flash('An error occurred. Guide could not be created.', 'danger')
    return render_template('reset_token.html', title='Reset Password', form=form)

travelbook/main/routes.py
from flask import render_template, request, abort, Blueprint
from travelbook.models import Travel


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@main.route('/travels')
def home():
    try:
        page = request.args.get('page', 1, type=int)
        travels=Travel.query.order_by(Travel.id.desc()).paginate(page=page, per_page=3)
    except Exception:
        abort(404)
    return render_template('home.html', travels=travels)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

travelbook/travels/routes.py
from flask import render_template, url_for, flash, request, redirect, abort, Blueprint
from flask_login import login_user, current_user, login_required
from travelbook import db
from travelbook.models import Travel
from travelbook.travels.forms import TravelForm


travels = Blueprint('travels', __name__)


# Show Travel
# ----------------------------------------------------------------#
@travels.route('/travels/<travel_id>')
def show_travel(travel_id):
    travel = Travel.query.get_or_404(travel_id)
    title = 'Trip: ' + travel.title
    return render_template('show_travel.html', travel=travel, title=title)

# Create Travel
# ----------------------------------------------------------------#
@travels.route('/travels/create', methods=['GET', 'POST'])
@login_required
def create_travel():
    form = TravelForm()
    if form.validate_on_submit():
        travel = Travel(title = form.title.data,
                        content = form.content.data,
                        guide = current_user)
        try:
            travel.insert()
            flash('Trip ' + form.title.data  + ' was successfully created!', 'success')
            return redirect('/travels')
        except:
            flash('An error occurred. Trip could not be created.', 'danger')
    return render_template('travel.html', title='New Travel', form=form, legend='New Travel')

# Update Travel
# ----------------------------------------------------------------#
@travels.route('/travels/<travel_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_travel(travel_id):
    travel=Travel.query.get_or_404(travel_id)
    if travel.guide != current_user:
        abort(403)
    form = TravelForm()
    if form.validate_on_submit():
        travel.title = form.title.data
        travel.content = form.content.data
        try:
            travel.update()
            flash('Your travel has been updated!', 'success')
            return redirect(url_for('travels.show_travel', travel_id=travel.id))
        except:
            flash('An error occurred. Trip could not be updated.', 'danger')
    elif request.method == 'GET':
        form.title.data = travel.title
        form.content.data = travel.content
    title = 'Trip ' + travel.title

    return render_template('travel.html', form=form, travel=travel,
                                title=title, legend='Update Travel')

# Delete Travel
# ----------------------------------------------------------------#
@travels.route('/travels/<travel_id>/delete', methods=['POST', 'DELETE'])
def delete_travel(travel_id):
    travel = Travel.query.get_or_404(travel_id)
    try:
        travel.delete()
        flash('Deleted!', 'success')
    except:
        flash('There was a problem deleting that guide', 'danger')
    return redirect(url_for('main.travels'))

travelbook/templates/account.html
{% extends 'layout.html' %}
{% block content %}
  <div class='content-section pt-4'>
  <div class='media'>
    <img class='rounded-circle account-img' src='{{ image_file }}'>
    <div class='media-body'>
      <h2 class='account-heading'>{{ current_user.name }} {{ current_user.surname }}</h2>
      <p class='text-secondary'>{{ current_user.email }}</p>
    </div>
  </div>
    <form method='post' class='form' enctype='multipart/form-data'>
      {{ form.hidden_tag() }}
      <fieldset class='form-group'>
          <legend class='border-bottom mb-4'>Account info</legend>
          <div class='form-group'>
              {{ form.name.label(class='form-control-label') }}
              {% if form.name.errors %}
                  {{ form.name(class='form-control form-control-lg is-invalid') }}
                  <div class='invalid-feedback'>
                      {% for error in form.name.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.name(class='form-control form-control-lg') }}
              {% endif %}
          </div>

          <div class='form-group'>
              {{ form.surname.label(class='form-control-label') }}
              {% if form.surname.errors %}
                  {{ form.surname(class='form-control form-control-lg is-invalid') }}
                  <div class='invalid-feedback'>
                      {% for error in form.surname.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.surname(class='form-control form-control-lg') }}
              {% endif %}
          </div>

          <div class='form-group'>
              {{ form.phone.label(class='form-control-label') }}
              {% if form.phone.errors %}
                  {{ form.phone(class='form-control form-control-lg is-invalid') }}
                  <div class='invalid-feedback'>
                      {% for error in form.phone.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.phone(class='form-control form-control-lg') }}
              {% endif %}
          </div>

          <div class='form-group'>
              {{ form.email.label(class='form-control-label') }}
              {% if form.email.errors %}
                  {{ form.email(class='form-control form-control-lg is-invalid') }}
                  <div class='invalid-feedback'>
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.email(class='form-control form-control-lg') }}
              {% endif %}
          </div>
          <div class='form-group'>
              {{ form.picture.label() }}
              {{ form.picture(class='form-control-file') }}
              {% if form.picture.errors %}
                  {% for error in form.picture.errors %}
                      <span class='text-danger'>{{ error }}</span></br>
                  {% endfor %}
              {% endif %}
          </div>
      </fieldset>
      <div class="row">
        <div class='form-group'>
            {{ form.submit(class='btn btn-primary', style='background-color: #20407b;') }}
        </div>
        <div class='form-group'>
            <button type="button" class='btn btn-danger ml-2' data-toggle='modal' data-target='#deleteModal' style='background-color: #b20c0c;'>Delete</button>
        </div>
      </div>
  </form>
</div>

<!-- Modal -->
<div class='modal fade' id='deleteModal' tabindex='-1' role='dialog' aria-labelledby='deleteModalLabel' aria-hidden='true'>
<div class='modal-dialog' role='document'>
	<div class='modal-content'>
		<div class='modal-header'>
			<h5 class='modal-title' id='deleteModalLabel'>Delete Account?</h5>
			<button type='button' class='close' data-dismiss='modal' aria-label='Close'>
				<span aria-hidden='true'>&times;</span>
			</button>
		</div>
		<div class='modal-footer'>
			<button type='button' class='btn btn-secondary' data-dismiss='modal'>Close</button>
			<form action='{{ url_for('guides.delete_guide', guide_id=current_user.id) }}' method='POST'>
				<input class='btn btn-danger' type='submit' value='Delete'>
			</form>
		</div>
	</div>
</div>
</div>

{% endblock content %}

travelbook/templates/guide_travels.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">My travels ({{ travels.total }})</h1>
    {% for travel in travels.items %}
        <article class="media content-section">
          <div class="media-body">
            <h2><a href="/travels/{{ travel.id }}" class="article-title">{{ travel.title }}</a></h2>
            <p class="article-content">{{ travel.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in travels.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if travels.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('guides.guide_travels', name=guide.name, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('guides.guide_travels', name=guide.name, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

travelbook/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" type="text/css">

    {% if title %}
      <title>Travel book - {{ title }}</title>
    {% else %}
      <title>Travel book</title>
    {% endif %}
  </head>
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
    {% if messages %}
      {% for category, message in messages %}
        {% if category == 'message' %}
          <div class="alert alert-warning" role="alert">
        {% else %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {% endif %}
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  </div>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-color: #20407b;">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">TravelBook</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('guides.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('guides.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('guides.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('guides.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Menu</h3>
            <p class='text-muted'>
              <ul class="list-group">
                {% if current_user.is_authenticated %}
                  <li class="list-group-item list-group-item-light"><a href="/my_travels">My Travels</a></li>
                  <li class="list-group-item list-group-item-light"><a href="/travels/create">New Travel</a></li>
                  <li class="list-group-item list-group-item-light"><a href="/travels">Travels</a></li>
                  <li class="list-group-item list-group-item-light"><a href="/guides">Guides</a></li>
                {% else %}
                  <li class="list-group-item list-group-item-light"><a href="/travels">Travels</a></li>
                  <li class="list-group-item list-group-item-light"><a href="/guides">Guides</a></li>
                  {% endif %}
              </ul>
            </p>
          </div>
      </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

travelbook/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class='content-section'>
        <form method='POST' action=''>
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Log In</legend>

                <div class='form-group'>
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class='form-group'>
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class='form-check'>
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
                <small class='text-muted ml-2'>
                    <a href='{{ url_for('guides.reset_request') }}'>Forgot Password?</a>
                </small>
            </div>
        </form>

    </div>
    <div class='border-top pt-3'>
        <small class='text-muted'>
            Need An Account? <a class='ml-2' href='{{ url_for('guides.register') }}'>Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

travelbook/templates/show_guide.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section pt-4">
	<div class="media">
		<img class="rounded-circle account-img" src="{{ guide.image_file }}" alt="Guide Image">
		<div class="media-body">
			<h2 class="account-heading">{{ guide.name }} {{ guide.surname }}</h2>
			<p class="text-secondary form-group">
				<strong>ID: </strong>{{ guide.id }}<br>
				{% if guide.phone %}<strong> Phone: </strong>{{ guide.phone }}{% else %}No Phone{% endif %}  <br>
    		{% if guide.email %}<strong> Email: </strong>{{ guide.email }}{% else %}No email{% endif %}
  		</p>
		</div>
	</div>
</div>
<div class="content-section">
	<h2 class="monospace">{% if travels %} Available Trips: {% else %} No Available Trips {% endif %} </h2>
		{%for travel in travels %}
			<h5><a href="/travels/{{ travel.id }}">{{ travel.title }}</a></h5>
		{% endfor %}
</div>
<div class="mt-3">
	<button class="btn btn-danger ml-2" data-toggle="modal" data-target="#deleteModal" style="background-color: #b20c0c; width: 100px;">Delete</button>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h5 class="modal-title" id="deleteModalLabel">Delete Guide?</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			<form action="{{ url_for('guides.delete_guide', guide_id=guide.id) }}" method="POST">
				<input class="btn btn-danger" type="submit" value="Delete">
			</form>
		</div>
	</div>
</div>
</div>






{% endblock %}